---
- name: Copy file to target servers
  hosts: all
  become: true
  tasks:
    # Ensure website folder exists
    - name: Ensure subfolder exists
      ansible.builtin.file:
        path: /www/swim
        owner: github-actions
        group: www-data
        state: directory
        mode: '0775'

    - name: Copy files
      ansible.posix.synchronize:
        src: "../{{ repositoryPath }}/"
        dest: /www/swim
        rsync_opts:
        - "--chmod=F644"

- name: Restart nginx
  hosts: all
  become: true
  tasks:
    - name: Restart nginx service
      ansible.builtin.service:
        name: nginx
        state: restarted

    # Handle certificates
