name: Deploy Site
on:
  # Runs on pushes targeting the default branch
  push:
    branches: ['main']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
    build-and-deploy:
        name: Build and deploy
        environment: Staging
        runs-on: ubuntu-latest
        steps:

        - name: Checkout
          uses: actions/checkout@v4

        - name: Set up Node
          uses: actions/setup-node@v4
          with:
            node-version: 20

        - name: Install dependencies
          run: npm install
        
        - name: Build app
          run: npm run build

        - name: Install Ansible
          shell: bash
          run: |
            sudo apt update
            sudo apt install -y ansible

        - name: Load deploy key
          uses: webfactory/ssh-agent@v0.9.0
          with:
            ssh-private-key: ${{ secrets.SSH_KEY }}

        - name: Run playbook
          run: ansible-playbook -i staging, .playbook/playbook.yml -u github-actions --inventory .playbook/inventory --extra-vars repositoryPath=$GITHUB_WORKSPACE
