name: Deploy Site
on:
  # Runs on pushes targeting the default branch
  push:
    branches: ['main']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    environment:
      name: production
    runs-on: self-hosted
    steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Set up Node
          uses: actions/setup-node@v3
        - name: Install dependencies
          run: npm install
        - name: Build
          run: npm run build
